# Generated by Django 4.1 on 2022-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='null')),
                ('title', models.CharField(max_length=150)),
                ('create_ad', models.DateField(auto_now_add=True)),
                ('update_ad', models.DateField(auto_now=True)),
            ],
        ),
    ]
